openapi: 3.0.3
info:
  title: Skills Framework API
  version: 1.0.12
tags:
  - name: Data APIs
    description: To supply information about job roles and skills in line with Industry Transformation Maps
  - name: Mapping APIs
    description: APIs for skills mapping between different frameworks
paths:
  /skillsFramework/jobs:
    get:
      summary: Get job role details
      description: Retrieve job role details, including description, critical work functions, key tasks, skills, and performance expectations.
      tags:
        - Data APIs
      parameters:
      
        - name: sector_title
          in: query
          required: false
          description: Title of the sector, as defined in the Skills Framework, where the job role resides in.
          schema:
            type: string
          example: "Wholesale Trade"
          
        - name: track_title
          in: query
          required: false
          description: Title of the track, as defined in the Skills Framework, where the job role resides in.
          schema:
            type: string
          example: "Finance and Regulations"
          
        - name: jobrole_title
          in: query
          required: false
          description: Title of the job role as defined in the Skills Framework.
          schema:
            type: string
          example: "Head of Trade Finance"    
          
        - name: keytask_content
          in: query
          required: false
          description: Key tasks, residing in the critical work function of the job role, as defined in the Skills Framework.
          schema:
            type: string
          example: "Manage department's recruitment and retention efforts"
          
        - name: skill_title
          in: query
          required: false
          description: Title of the skill, as defined in the Skills Framework, required by the job role.
          schema:
            type: string
          example: "Organisational Analysis"
          
        - name: sfw_version
          in: query
          required: false
          description: Version of the skill in the Skills Framework.
          schema:
            type: string
          example: "sfw1.0"
          
      responses:
        '200':
          description: Job role details retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/jobs'
        '400':
          description: Invalid request
        '404':
          description: Job role not found
        '500':
          description: Server error
          
  /skillsFramework/skills:
    get:
      summary: Get skills details
      description: Retrieve skill details, including proficiency level, skill type, and descriptions.
      tags:
        - Data APIs
      parameters:
      
        - name: sector_title
          in: query
          required: false
          description: Title of the sector, as defined in the Skills Framework, where the skill resides in.
          schema:
            type: string
          example: "Wholesale Trade"
          
        - name: skill_title
          in: query
          required: false
          description: Title of the skill as defined in the Skills Framework.
          schema:
            type: string
          example: "Organisational Analysis"
                
        - name: tsc_code
          in: query
          required: false
          description: A unique identifier for skills.
          schema:
            type: string
          example: "WST-SPI-5002-1.1"
          
        - name: skill_type
          in: query
          required: false
          description: Classification of the skill (e.g., TSC, CCS)
          schema:
            type: string
          example: "tsc"
          
        - name: sfw_version
          in: query
          required: false
          description: Version of the associated skill in the Skills Framework.
          schema:
            type: string
          example: "sfw1.0"
          
      responses:
        '200':
          description: Skills details retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/skills'
        '400':
          description: Invalid request
        '404':
          description: Skill not found
        '500':
          description: Server error
          
components:
  schemas:
    jobs:
      type: object
      properties:
      
        sector_title:
          type: string
          description: Title of the sector, as defined in the Skills Framework, where the job role resides in.
          example: "Wholesale Trade"
          
        track_title:
          type: string
          description: Title of the track, as defined in the Skills Framework, where the job role resides in.
          example: "Finance and Regulations"
          
        jobrole_title:
          type: string
          description: Title of the job role as defined in the Skills Framework.
          example: "Head of Trade Finance"
          
        jobrole_description:
          type: string
          description: Description of the job role as defined in the Skills Framework.
          example: "The Head of Trade Finance assumes responsibility for driving execution of the organisation's trade finance activities and strategies. He/She is expected to have extensive knowledge of trade flows, trade settlements and trade finance operations. He oversees negotiations with financial institutions on trade finance. He is expected to have strong stakeholder engagement skills, team leadership capabilities and deep trade finance knowledge, both locally and globally."   
        
        workfunction_content:
          type: string
          description: Critical work functions of the job role as defined in the Skills Framework.
          example: "Support human resource, technology and/or finance operations"
        
        keytask_content:
          type: string
          description: Key tasks, residing in the critical work function of the job role, as defined in the Skills Framework.
          example: "Manage department's recruitment and retention efforts"
        
        performance_expectations:
          type: string
          description: Industry-defined performance standards for the job role, including statutory requirements.
          example: ""
        
        skill_title:
          type: string
          description: Title of the skill, as defined in the Skills Framework, required by the job role.
          example: "Organisational Analysis"
        
        proficiency_level:
          type: string
          description: Proficiency level of the associated skill, as defined in the Skills Framework, rated numerically or by category (e.g., 1, 2, 3, 4, 5, 6, basic, intermediate, advanced), required by the job role.
          example: "5"
        
        tsc_code:
          type: string
          description: A unique identifier for skills.
          example: "WST-SPI-5002-1.1"

        skill_type:
          type: string
          description: Classification of the associated skill (e.g., TSC, CCS).
          example: "tsc"

        sfw_version:
          type: string
          description: Version of the associated skill in the Skills Framework.
          example: "sfw1.0"
          
    skills:
      type: object
      properties:
          
        sector_title:
          type: string
          description: Title of the sector, as defined in the Skills Framework, where the job role resides in.
          example: "Wholesale Trade"
          
        skill_title:
          type: string
          description: Title of the skill as defined in the Skills Framework.
          example: "Organisational Analysis"
          
        skill_description:
          type: string
          description: Description of the skill as defined in the Skills Framework.
          example: "Evaluate factors that can affect the organization's performance as well as strategically assessing the organization's own resources and potential for improvement"
        
        proficiency_level:
          type: string
          description: Proficiency level of the associated skill, as defined in the Skills Framework, rated numerically or by category (e.g., 1, 2, 3, 4, 5, 6, basic, intermediate, advanced).
          example: "5"
        
        proficiency_description:
          type: string
          description: Description of the proficiency level for the associated skill.
          example: "Establish team effectiveness and manage partnerships to create a cooperative working environment which enables the achievement of goals"

        tsc_code:
          type: string
          description: A unique identifier for skills.
          example: "WST-SPI-5002-1.1"

        skill_type:
          type: string
          description: Classification of the skill (e.g., TSC, CCS).
          example: "tsc"
          
        sfw_version:
          type: string
          description: Version of the associated skill in the Skills Framework.
          example: "sfw1.0"

        is_sfs_emerging:
          type: boolean
          description: Indicates whether the skill is part of the SkillsFuture Series list of emerging skills.
          example: false

        is_casl:
          type: boolean
          description: Indicates whether the skill is part of the Course Approval Skills List.
          example: true
          
        ability_knowledge_range_of_application_classification:
          type: string
          description: Classification of the individual statements of ability, knowledge, or range_of_application.
          example: "knowledge"
        
        ability_knowledge_range_of_application_item:
          type: string
          description: Individual statements of ability, knowledge, or range_of_application.
          example: "Stakeholder management strategies"
